import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainProviders from "@/providers/provider";
import Layout from "@/components/Layout/Layout";
import ListFetch from "@/Services/ListFetch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const getProfileData = await ListFetch.getProfileData()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainProviders>
          <Layout profile={getProfileData}>
            {children}
          </Layout>
        </MainProviders>
      </body>
    </html>
  );
}
